// Generated by CoffeeScript 1.6.3
(function() {
  var M, Slime, Vector, ctx, global, _Vector;

  global = this;

  M = Math;

  ctx = null;

  CanvasRenderingContext2D.prototype.vBezierCurveTo = function(v1, v2, v3) {
    return this.bezierCurveTo(v1.x, v1.y, v2.x, v2.y, v3.x, v3.y);
  };

  _Vector = (function() {
    function _Vector(x, y) {
      this.x = x;
      this.y = y;
    }

    _Vector.prototype.add = function(v) {
      return new _Vector(this.x + v.x, this.y + v.y);
    };

    _Vector.prototype.add_ = function(v) {
      this.x += v.x;
      this.y += v.y;
    };

    _Vector.prototype.sub = function(v) {
      return new _Vector(this.x - v.x, this.y - v.y);
    };

    _Vector.prototype.sub_ = function(v) {
      this.x -= v.x;
      this.y -= v.y;
    };

    _Vector.prototype.mul = function(k) {
      return new _Vector(this.x * k, this.y * k);
    };

    _Vector.prototype.rotate = function(rad) {
      var x, y;
      x = M.cos(rad) * this.x - M.sin(rad) * this.y;
      y = M.sin(rad) * this.x + M.cos(rad) * this.y;
      return new _Vector(x, y);
    };

    _Vector.prototype.rotate_ = function(rad) {
      var x, y;
      x = M.cos(rad) * this.x - M.sin(rad) * this.y;
      y = M.sin(rad) * this.x + M.cos(rad) * this.y;
      this.x = x;
      this.y = y;
    };

    return _Vector;

  })();

  Vector = function(x, y) {
    return new _Vector(x, y);
  };

  global.V = Vector;

  Slime = (function() {
    function Slime(x, y, r) {
      this.x = x;
      this.y = y;
      this.r = r != null ? r : 50;
      this.color = 'rgba(0, 210, 255, 0.7)';
    }

    Slime.prototype.draw = function() {
      var a, dv, dw, i, v, w, _i;
      ctx.beginPath();
      ctx.setTransform(1, 0, 0, 1, this.x, this.y);
      ctx.fillStyle = this.color;
      v = Vector(0, this.r);
      a = M.sqrt(3) / 2;
      dv = v.rotate(M.PI / 2).mul(a);
      ctx.moveTo(v.x, v.y);
      for (i = _i = 0; _i < 3; i = ++_i) {
        w = v.rotate(M.PI * 2 / 3);
        dw = w.rotate(M.PI / 2).mul(a);
        ctx.vBezierCurveTo(v.add(dv), w.sub(dw), w);
        v = w;
        dv = dw;
      }
      return ctx.fill();
    };

    Slime.prototype.update = function() {};

    return Slime;

  })();

  window.onload = function() {
    var canvas, fps, height, mainLoop, slime, width;
    canvas = document.getElementById('canvas');
    width = canvas.width;
    height = canvas.height;
    ctx = canvas.getContext('2d');
    fps = 30;
    global.slime = slime = new Slime(width / 2, height / 2);
    mainLoop = function() {
      ctx.clearRect(-width, -height, width * 2, height * 2);
      slime.draw();
      slime.update();
      return setTimeout(mainLoop, 1 / fps);
    };
    return mainLoop();
  };

}).call(this);
