// Generated by CoffeeScript 1.6.3
(function() {
  var M, Slime, ctx, global;

  global = this;

  M = Math;

  ctx = null;

  Slime = (function() {
    function Slime(x, y, r) {
      this.x = x;
      this.y = y;
      this.r = r != null ? r : 50;
      this.color = 'rgba(0, 210, 255, 0.7)';
    }

    Slime.prototype.draw = function() {
      ctx.beginPath();
      ctx.fillStyle = this.color;
      ctx.arc(this.x, this.y, this.r, 0, M.PI * 2, true);
      return ctx.fill();
    };

    return Slime;

  })();

  window.onload = function() {
    var canvas, fps, height, mainLoop, slime, width;
    canvas = document.getElementById('canvas');
    width = canvas.width;
    height = canvas.height;
    ctx = canvas.getContext('2d');
    fps = 30;
    global.slime = slime = new Slime(width / 2, height / 2);
    mainLoop = function() {
      ctx.clearRect(0, 0, width, height);
      slime.draw();
      return setTimeout(mainLoop, 1 / fps);
    };
    return mainLoop();
  };

}).call(this);
